version: '3.7'

services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: sh -c "yarn start"
    volumes:
      - ./frontend:/app
    stdin_open: true

  api:
    depends_on:
      - mysql
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    command: sh -c "mix ecto.setup && mix phx.server"
    volumes:
      - ./backend:/app
      - ~/.aws:/root

  mysql:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
